import os
import uuid
from datetime import datetime
from fpdf import FPDF

os.makedirs("generated", exist_ok=True)

class ReferralPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(0, 120, 100)
        self.cell(0, 10, "SAHAYAK HEALTH REFERRAL", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, "AI Co-Pilot for ASHA Workers | Solapur District", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_draw_color(0, 120, 100)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by Sahayak AI | For official use only | Not a clinical diagnosis", align="C")


def generate_referral_pdf(letter: dict, patient_data: dict) -> str:
    pdf = ReferralPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    date_str = datetime.now().strftime("%d %B %Y")

    # ── Meta info ─────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(95, 7, f"Date: {date_str}")
    pdf.cell(95, 7, f"Ref No: SAH-{str(uuid.uuid4())[:6].upper()}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # ── Patient details box ───────────────────────────────────────────────────
    pdf.set_fill_color(245, 250, 248)
    pdf.set_draw_color(0, 120, 100)
    pdf.rect(10, pdf.get_y(), 190, 28, style="FD")
    pdf.set_xy(14, pdf.get_y() + 4)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(0, 80, 70)
    pdf.cell(0, 6, "PATIENT INFORMATION", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(14)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(65, 6, f"Name: {patient_data['patient_name']}")
    pdf.cell(65, 6, f"Age: {patient_data['patient_age']} years")
    pdf.cell(65, 6, f"Village: {patient_data['patient_village']}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── English letter ────────────────────────────────────────────────────────
    eng = letter.get("english", {})
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 80, 70)
    pdf.cell(0, 8, "REFERRAL LETTER (English)", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(0, 7, eng.get("salutation", "To the Medical Officer,"))
    pdf.ln(2)
    pdf.multi_cell(0, 7, eng.get("body", ""))
    pdf.ln(2)
    pdf.multi_cell(0, 7, eng.get("closing", ""))
    pdf.ln(2)
    pdf.multi_cell(0, 7, eng.get("signature", f"ASHA Worker: {patient_data['asha_name']}"))
    pdf.ln(6)

    # ── Divider ───────────────────────────────────────────────────────────────
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── Marathi note (text only — fpdf2 doesn't support Devanagari without TTF) ──
    mr = letter.get("marathi", {})
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 80, 70)
    pdf.cell(0, 8, "REFERRAL LETTER (Marathi - see app for Devanagari)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 6, "Note: Full Marathi text is available in the Sahayak app. This PDF contains the English version for PHC records.")
    pdf.ln(4)

    # ── Clinical findings ─────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 80, 70)
    pdf.cell(0, 8, "CLINICAL FINDINGS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(0, 7, patient_data.get("findings", ""))
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(180, 30, 30)
    pdf.cell(0, 8, "RECOMMENDATION", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(0, 7, patient_data.get("recommendation", ""))
    pdf.ln(6)

    # ── Disclaimer ────────────────────────────────────────────────────────────
    pdf.set_fill_color(255, 250, 235)
    pdf.set_draw_color(200, 150, 0)
    y = pdf.get_y()
    pdf.rect(10, y, 190, 14, style="FD")
    pdf.set_xy(14, y + 3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 80, 0)
    pdf.multi_cell(182, 5, "DISCLAIMER: This referral is generated by Sahayak AI as a clinical support tool. It does not constitute a medical diagnosis. Final clinical decisions must be made by a qualified medical professional.")

    filename = f"referral_{str(uuid.uuid4())[:8]}.pdf"
    pdf.output(f"generated/{filename}")
    return filename
